version: '3.8'

services:
  app:
    build: .
    container_name: weather-forecast-chatbot
    ports:
      - "5000:5000"
    environment:
      - DATA_DIR=/app/data
      - HF_TOKEN=${HF_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - OPEN_WEATHER_MAP_API=${OPEN_WEATHER_MAP_API}
      - NCEI_API_KEY=${NCEI_API_KEY}
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  ngrok:
    image: wernight/ngrok
    container_name: weather-ngrok
    depends_on:
      - app
    volumes:
      - ./ngrok.yml:/ngrok/ngrok.yml:ro
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ngrok start --all --config /ngrok/ngrok.yml


